// R6.3 – Admin (Banner/Voucher in-place)
import { api } from './lib/api.js';
const views={products:document.querySelector('#view-products'),banners:document.querySelector('#view-banners'),vouchers:document.querySelector('#view-vouchers')};
document.querySelectorAll('.nav').forEach(btn=>{btn.addEventListener('click',()=>{const v=btn.getAttribute('data-view');Object.values(views).forEach(el=>el?.classList.add('hidden'));views[v]?.classList.remove('hidden');if(v==='banners')listBanners();if(v==='vouchers')listVouchers()})});
const modal=document.querySelector('#modal');const mTitle=document.querySelector('#modal-title');const mBody=document.querySelector('#modal-body');
function openModal(title,bodyHTML,onOk){mTitle.textContent=title;mBody.innerHTML=bodyHTML;modal.classList.remove('hidden');const cleanup=()=>{modal.classList.add('hidden');['modal-ok','modal-cancel'].forEach(id=>{const node=document.getElementById(id);const clone=node.cloneNode(true);node.replaceWith(clone)})};document.getElementById('modal-cancel').addEventListener('click',cleanup);document.getElementById('modal-ok').addEventListener('click',async()=>{try{await onOk?.()}finally{cleanup()}});const upBtn=document.querySelector('#btn-upload-image');const fileEl=document.querySelector('#file-image');if(upBtn&&fileEl){upBtn.addEventListener('click',async()=>{if(!fileEl.files?.length)return alert('Chọn ảnh trước!');const url=await uploadImage(fileEl.files[0]);const urlInput=document.querySelector('#image');urlInput.value=url;const pre=document.querySelector('#preview');if(pre)pre.src=url})}}
const CLOUD_NAME='dtemskptf';const UPLOAD_PRESET='unsigned';
async function uploadImage(file){if(!CLOUD_NAME||!UPLOAD_PRESET){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}const form=new FormData();form.append('file',file);form.append('upload_preset',UPLOAD_PRESET);const r=await fetch(`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/auto/upload`,{method:'POST',body:form});const j=await r.json();if(!j.secure_url)throw new Error('Upload thất bại');return j.secure_url}
async function listBanners(){const wrap=document.querySelector('#banner-list');wrap.innerHTML='<div class="muted">Đang tải...</div>';const r=await api('/banners');const items=r?.items||[];wrap.innerHTML=items.map(b=>`<div class="card"><img src="${b.image||''}" alt="" class="thumb"><div class="grow"><div class="title">${b.title||''}</div><div class="muted">${b.link||''}</div></div><div class="row"><button class="btn" data-act="edit" data-id="${b.id}">Sửa</button><button class="btn btn-warn" data-act="del" data-id="${b.id}">Xóa</button></div></div>`).join('')||'<div class="muted">Chưa có banner</div>';wrap.querySelectorAll('[data-act=edit]').forEach(btn=>{btn.onclick=()=>editBanner(btn.dataset.id,items.find(x=>x.id===btn.dataset.id))});wrap.querySelectorAll('[data-act=del]').forEach(btn=>{btn.onclick=async()=>{if(!confirm('Xóa banner?'))return;await api(`/banners/${btn.dataset.id}`,{method:'DELETE'});listBanners()}})}
function editBanner(id,data={}){openModal(id?'Sửa banner':'Thêm banner',`<div class="form"><label>Tiêu đề<input id="title" value="${data.title||''}"></label><label>Liên kết<input id="link" value="${data.link||''}"></label><label>Ảnh (URL) <input id="image" value="${data.image||''}"></label><div class="row"><input id="file-image" type="file" accept="image/*"><button id="btn-upload-image" type="button" class="btn">Tải ảnh</button></div><img id="preview" src="${data.image||''}" class="preview"></div>`,async()=>{const payload={title:document.querySelector('#title').value.trim(),link:document.querySelector('#link').value.trim(),image:document.querySelector('#image').value.trim()};if(id)await api(`/banners/${id}`,{method:'PUT',body:payload});else await api('/banners',{method:'POST',body:payload});listBanners()})}
document.querySelector('#btn-add-banner')?.addEventListener('click',()=>editBanner(null,{}));
async function listVouchers(){const wrap=document.querySelector('#voucher-list');wrap.innerHTML='<div class="muted">Đang tải...</div>';const r=await api('/vouchers');const items=r?.items||[];wrap.innerHTML=items.map(v=>`<div class="card"><div class="grow"><div class="title">${v.code}</div><div class="muted">${v.type} ${v.value||''}</div></div><div class="row"><button class="btn" data-act="edit" data-id="${v.id}">Sửa</button><button class="btn btn-warn" data-act="del" data-id="${v.id}">Xóa</button></div></div>`).join('')||'<div class="muted">Chưa có voucher</div>';wrap.querySelectorAll('[data-act=edit]').forEach(btn=>{btn.onclick=()=>editVoucher(btn.dataset.id,items.find(x=>x.id===btn.dataset.id))});wrap.querySelectorAll('[data-act=del]').forEach(btn=>{btn.onclick=async()=>{if(!confirm('Xóa voucher?'))return;await api(`/vouchers/${btn.dataset.id}`,{method:'DELETE'});listVouchers()}})}
function editVoucher(id,data={}){openModal(id?'Sửa voucher':'Thêm voucher',`<div class="form"><label>Mã code<input id="code" value="${data.code||''}"></label><label>Loại<select id="type"><option value="percent" ${data.type==='percent'?'selected':''}>Phần trăm</option><option value="fixed" ${data.type==='fixed'?'selected':''}>Tiền cố định</option><option value="freeship" ${data.type==='freeship'?'selected':''}>Miễn phí ship</option></select></label><label>Giá trị<input id="value" type="number" step="1" value="${data.value??0}"></label><label>ĐH tối thiểu<input id="min" type="number" step="1" value="${data.min??0}"></label><label>Áp cho SP (id, cách nhau dấu phẩy)<input id="productIds" value="${(data.productIds||[]).join(',')}"></label><label>Hết hạn<input id="expired" type="date" value="${(data.expired||'').slice(0,10)}"></label></div>`,async()=>{const payload={code:document.querySelector('#code').value.trim(),type:document.querySelector('#type').value,value:+document.querySelector('#value').value||0,min:+document.querySelector('#min').value||0,productIds:document.querySelector('#productIds').value.split(',').map(s=>s.trim()).filter(Boolean),expired:document.querySelector('#expired').value||null};if(id)await api(`/vouchers/${id}`,{method:'PUT',body:payload});else await api('/vouchers',{method:'POST',body:payload});listVouchers()})}
document.querySelector('#btn-add-voucher')?.addEventListener('click',()=>editVoucher(null,{}));
views.products?.classList.remove('hidden');
