name: Deploy MINI (Zalo Mini App) to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/mini/**"
      - ".github/workflows/deploy-mini.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-mini-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (root, workspaces)
        run: npm ci
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Build MINI workspace
        run: npm -w apps/mini run build

      - name: Publish to Cloudflare Pages (MINI)
        uses: cloudflare/pages-action@v1
        with:
          apiToken:      ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:     ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName:   shv-mini
          directory:     apps/mini/dist
          gitHubToken:   ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

      # Không cần Upload Images/Videos trong Mini App vì Admin đã xử lý upload
