name: Deploy Worker (shv-api)

on:
  push:
    branches: [ "main" ]
    paths:
      - "workers/shv-api/**"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-worker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers/shv-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Wrangler
        run: npm i -g wrangler@3

      # ==== Kiểm tra môi trường ====
      - name: Echo env (debug)
        shell: bash
        run: |
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          if [ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then echo "API TOKEN: OK"; else echo "API TOKEN: MISSING"; fi

      # ==== Build và Deploy ====
      - name: Build dry-run (debug)
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
          SUPER_BASE:       ${{ secrets.SUPER_BASE }}
          WRANGLER_LOG:     debug
        run: wrangler deploy --dry-run

      - name: Deploy wrangler
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
          SUPER_BASE:       ${{ secrets.SUPER_BASE }}
          WRANGLER_LOG:     debug
        run: wrangler deploy

      # ==== Gửi Media (Hình ảnh/Video) ĐẾN Cloudinary đã có sẵn từ Admin - loại bỏ
      # (Bỏ bước upload media ở đây vì Admin đã xử lý)
      # - name: Upload media to Cloudinary
      #   run: |
      #     curl -X POST "https://shv-api.shophuyvan.workers.dev/upload" \
      #     -F "file=@path/to/your/image_or_video" \
      #     -H "Authorization: Bearer ${{ secrets.CLOUDINARY_API_TOKEN }}"
