name: Deploy Admin to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/admin/**"
      - ".github/workflows/deploy-admin.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-admin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Bước build Admin Panel nếu cần
      - name: Build Admin Panel
        working-directory: apps/admin
        run: |
          npm install
          npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: adminshophuyvan
          directory: apps/admin/dist  # Hoặc thư mục build của Admin Panel
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
