name: Deploy Admin to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/admin/**"
      - ".github/workflows/deploy-admin.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-admin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Nếu Admin có bước build, thêm ở đây
      # - name: Build Admin
      #   working-directory: apps/admin
      #   run: |
      #     npm ci
      #     npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:      ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:     ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName:   adminshophuyvan
          directory:     apps/admin
          gitHubToken:   ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

      # (Bước bổ sung để xử lý ảnh/video)
      - name: Upload Images/Videos to Cloudinary via API
        run: |
          curl -X POST "https://shv-api.shophuyvan.workers.dev/upload" \
          -F "file=@path/to/image_or_video" \
          -H "Authorization: Bearer ${{ secrets.CLOUDINARY_API_TOKEN }}"

      # (Nếu cần, thêm bước kiểm tra upload đã thành công)
      - name: Verify Image/Video Upload Success
        run: |
          # Gọi API của Worker hoặc kiểm tra kết quả upload
          curl -X GET "https://shv-api.shophuyvan.workers.dev/check-upload-status"
