name: Deploy Worker

on:
  push:
    branches: [ "main" ]
    paths:
      - "workers/shv-api/**"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-worker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers/shv-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Nếu project có package.json để bundle) – giữ lại, nếu không có thì bỏ
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        if: hashFiles('**/package.json') != ''
        run: npm ci

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # tên secret khớp với bạn đang dùng
          workingDirectory: workers/shv-api
          command: publish
