name: Deploy Worker
on:
  push:
    paths: ['shv-api/**']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shv-api
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm i -g wrangler@4
      # (tùy chọn) kiểm tra đăng nhập: dùng --account (không phải --account-id)
      - name: Whoami (debug)
        run: wrangler whoami --account $CLOUDFLARE_ACCOUNT_ID
      - name: Deploy
        run: wrangler deploy --config wrangler.toml --account-id $CLOUDFLARE_ACCOUNT_ID
