name: Deploy Worker

on:
  push:
    branches: [ main ]
    paths:
      - "workers/shv-api/**"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-worker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # (optional) nếu có package.json trong workers/shv-api
      - name: Install deps (if any)
        working-directory: workers/shv-api
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Wrangler whoami (check token/account)
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler@3 whoami
          echo "Account: $CLOUDFLARE_ACCOUNT_ID"

      - name: List KV namespaces (sanity check)
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler@3 kv namespace list || true

      - name: Dry-run build (see bundling errors)
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler@3 deploy --dry-run --log-level=debug

      - name: Deploy (prod)
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler@3 deploy --log-level=debug
