name: Deploy Worker (shv-api)

on:
  push:
    branches: [ "main" ]
    paths:
      - "workers/shv-api/**"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-worker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers/shv-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Wrangler
        run: npm i -g wrangler@3

      # Debug: kiểm tra secrets có mặt
      - name: Echo env (debug)
        shell: bash
        run: |
          echo "CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}"
          if [ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then echo "TOKEN: OK"; else echo "TOKEN: MISSING"; fi

      # Build thử: lộ lỗi JS/bindings nếu có
      - name: Build dry-run (debug)
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
          SUPER_BASE:       ${{ secrets.SUPER_BASE }}
        run: wrangler deploy --dry-run --verbose

      # Deploy thật (in log chi tiết)
      - name: Deploy wrangler
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
          SUPER_BASE:       ${{ secrets.SUPER_BASE }}
        run: wrangler deploy --verbose
