name: Deploy FE to Cloudflare Pages

on:
  workflow_dispatch:      # cho phép Run thủ công
  push:
    paths:
      - "apps/fe/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Nếu cần build FE (ví dụ Vite/Next):
      # - name: Install & Build
      #   working-directory: apps/fe
      #   run: |
      #     npm ci
      #     npm run build

      # Deploy lên Cloudflare Pages
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:   ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: shophuyvan1
          # Nếu có bước build: directory: apps/fe/dist
          # Nếu site tĩnh sẵn: trỏ đúng thư mục public của FE
          directory: apps/fe/dist
