# .github/workflows/deploy-admin.yml
name: Deploy Admin to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/admin/**"
      - ".github/workflows/deploy-admin.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-admin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Nếu Admin có bước build, thêm ở đây – và đổi 'directory' bên dưới trỏ vào thư mục output)
      # - name: Build Admin
      #   working-directory: apps/admin
      #   run: |
      #     npm ci
      #     npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:      ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:     ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName:   adminshophuyvan  # <- đúng tên project Pages cho Admin
          directory:     apps/admin       # <- hoặc đổi sang thư mục build (vd: apps/admin/dist)
          gitHubToken:   ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
