name: Deploy Worker

on:
  push:
    paths:
      - "workers/shv-api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      # 1) In ra cây thư mục & wrangler.toml để chắc chắn đúng đường dẫn
      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "---- workers/shv-api ----"
          ls -la workers/shv-api || true
          echo "---- wrangler.toml ----"
          cat workers/shv-api/wrangler.toml || true

      # 2) Cài Node rõ ràng (Wrangler 3 chạy tốt với Node 18/20)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Kiểm tra đăng nhập bằng token
      - name: Wrangler whoami
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 whoami --verbose

      # 4) Deploy trực tiếp (không dùng action wrapper để nhìn full log)
      - name: Deploy (direct)
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 deploy --verbose
