name: Deploy FE to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/fe/**"
      - ".github/workflows/deploy-fe.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-fe-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Nếu FE có bước build, thêm ở đây
      # - name: Build FE
      #   working-directory: apps/fe
      #   run: |
      #     npm ci
      #     npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:      ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:     ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName:   shophuyvan  # Tên đúng của project Pages cho FE
          directory:     apps/fe     # Hoặc đổi sang thư mục build (vd: apps/fe/dist)
          gitHubToken:   ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

      # ==== GỬI MEDIA (HÌNH ẢNH/VIDEO) ĐẾN CLOUDINARY (HOẶC R2) ====
      - name: Upload media to Cloudinary
        run: |
          curl -X POST "https://shv-api.shophuyvan.workers.dev/upload" \
          -F "file=@path/to/image_or_video" \
          -H "Authorization: Bearer ${{ secrets.CLOUDINARY_API_TOKEN }}"

      # ==== (TUỲ CHỌN) KIỂM TRA KẾT QUẢ UPLOAD ====
      - name: Verify Upload to Cloudinary
        run: |
          curl -X GET "https://shv-api.shophuyvan.workers.dev/check-upload-status"
