name: Deploy Worker (shv-api)

on:
  push:
    branches: [ "main" ]
    paths:
      - "workers/shv-api/**"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-worker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers/shv-api

    steps:
            - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Wrangler
        run: npm i -g wrangler@3

      # Debug: in env để chắc chắn secrets đang có
      - name: Echo env (debug)
        run: |
          echo "CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}"
          echo "CLOUDFLARE_API_TOKEN length: $([[ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]] && echo OK || echo MISSING)"
        shell: bash

      # Build thử để lộ lỗi JS/bindings (nếu có)
      - name: Build dry-run (debug)
        run: wrangler deploy --dry-run --verbose
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # CHỈ cần nếu bạn không set ở Dashboard → Variables
          SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
          SUPER_BASE:       ${{ secrets.SUPER_BASE }}

      # Deploy thật (có log chi tiết)
      - name: Deploy wrangler
        run: wrangler deploy --verbose
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
          SUPER_BASE:       ${{ secrets.SUPER_BASE }}
