name: Deploy Admin to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/admin/**"
      - ".github/workflows/deploy-admin.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:   ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: adminshophuyvan
          # Nếu trong repo admin của bạn có thư mục dist/ thì đặt 'apps/admin/dist'
          directory:  apps/admin
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
