name: Deploy Worker

on:
  workflow_dispatch:
  push:
    paths:
      - "workers/shv-api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:      ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:     ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: workers/shv-api
          command: deploy
