name: Deploy Worker

on:
  push:
    paths:
      - "workers/shv-api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree + wrangler.toml
        run: |
          pwd
          ls -la
          echo "---- workers/shv-api ----"
          ls -la workers/shv-api || true
          echo "---- wrangler.toml ----"
          cat workers/shv-api/wrangler.toml || true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Wrangler version
        working-directory: workers/shv-api
        run: npx --yes wrangler@3 --version

      # ⚠️ Không dùng --verbose ở đây
      - name: Whoami
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 whoami

      - name: Deploy (direct)
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 deploy --verbose
