  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: "20"

  - name: Install Wrangler
    run: npm i -g wrangler@3

  # In biến môi trường để chắc chắn đã có
  - name: Echo env (debug)
    run: |
      echo "CF_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}"
      echo "CLOUDFLARE_API_TOKEN length=${{ secrets.CLOUDFLARE_API_TOKEN && 1 || 0 }}"
    shell: bash

  # Build thử trước (in log lỗi nếu có cú pháp)
  - name: Build dry-run (debug)
    run: wrangler deploy --dry-run --verbose
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      # chỉ cần nếu không set ở Dashboard
      SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
      SUPER_BASE:       ${{ secrets.SUPER_BASE }}

  # Deploy thật (có log chi tiết)
  - name: Deploy wrangler
    run: wrangler deploy --verbose
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      SHIPPING_API_KEY: ${{ secrets.SHIPPING_API_KEY }}
      SUPER_BASE:       ${{ secrets.SUPER_BASE }}
