name: Deploy Worker
on:
  push:
    paths:
      - 'shv-api/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shv-api
    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Put secrets
        run: |
          echo "${{ secrets.GEMINI_API_KEY }}" | wrangler secret put GEMINI_API_KEY --config wrangler.toml
          echo "${{ secrets.FIREBASE_PROJECT_ID }}" | wrangler secret put FIREBASE_PROJECT_ID --config wrangler.toml
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" | wrangler secret put GOOGLE_SERVICE_ACCOUNT_JSON --config wrangler.toml
          echo "${{ secrets.ADMIN_TOKEN }}" | wrangler secret put ADMIN_TOKEN --config wrangler.toml
          echo "${{ secrets.CLOUDINARY_API_KEY }}" | wrangler secret put CLOUDINARY_API_KEY --config wrangler.toml
          echo "${{ secrets.CLOUDINARY_API_SECRET }}" | wrangler secret put CLOUDINARY_API_SECRET --config wrangler.toml
          echo "${{ secrets.CLOUDINARY_CLOUD_NAME }}" | wrangler secret put CLOUDINARY_CLOUD_NAME --config wrangler.toml
          echo "${{ secrets.CLOUDINARY_UPLOAD_PRESET }}" | wrangler secret put CLOUDINARY_UPLOAD_PRESET --config wrangler.toml

      - name: Publish
        run: wrangler publish --account-id ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} --config wrangler.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
