name: Deploy FE to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/fe/**"
      - ".github/workflows/deploy-fe.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy-fe-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Kiểm tra thư mục làm việc hiện tại
      - name: Print current working directory
        run: |
          echo "Current directory: $(pwd)"  # In ra thư mục làm việc hiện tại

      # Liệt kê tất cả các tệp trong thư mục làm việc
      - name: List all files in the current directory
        run: |
          ls -al  # Liệt kê tất cả các tệp trong thư mục hiện tại

      # Kiểm tra tệp có tồn tại hay không
      - name: Check if file exists
        run: |
          if [ -f "apps/fe/images/your_image_or_video.jpg" ]; then  # Kiểm tra tệp có tồn tại không
            echo "File exists"
          else
            echo "File does not exist"
            exit 1  # Nếu tệp không tồn tại, dừng quy trình
          fi

      # Tiến hành deploy sau khi kiểm tra
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:      ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:     ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName:   shophuyvan  # Tên đúng của project Pages cho FE
          directory:     apps/fe     # Hoặc đổi sang thư mục build (vd: apps/fe/dist)
          gitHubToken:   ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
      
      # Upload image/video to Cloudinary (sau khi đảm bảo tệp tồn tại)
      - name: Upload Images/Videos to Cloudinary
        run: |
          curl -X POST "https://shv-api.shophuyvan.workers.dev/upload" \
          -F "file=@apps/fe/images/your_image_or_video.jpg" \
          -H "Authorization: Bearer ${{ secrets.CLOUDINARY_API_TOKEN }}"
