name: Deploy FE to Cloudflare Pages

on:
  push:
    branches: [ main ]
    paths:
      - "apps/fe/**"
      - ".github/workflows/deploy-fe.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:   ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: shophuyvan1
          directory:  apps/fe
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
