name: Deploy Admin to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - "apps/admin/**"
      - ".github/workflows/deploy-admin.yml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) CÀI PNPM TRƯỚC
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      # 2) SAU KHI CÓ PNPM, MỚI DÙNG setup-node + cache pnpm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/admin/pnpm-lock.yaml

      - name: Install
        working-directory: apps/admin
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: apps/admin
        run: pnpm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: adminshophuyvan
          directory: apps/admin/dist
