# .github/workflows/deploy-fe.yml
name: Deploy FE to Cloudflare Pages
on:
  push:
    paths:
      - 'apps/fe/**'
      - '.github/workflows/deploy-fe.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile
        working-directory: apps/fe

      - name: Build
        run: pnpm build
        working-directory: apps/fe     # output: apps/fe/dist

      - name: Publish to Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: shophuyvan1
          directory: apps/fe/dist
