# .github/workflows/deploy-worker.yml
name: Deploy Worker (shv-api)

on:
  push:
    branches: [ "main" ]
    paths:
      - "workers/shv-api/**"
      - ".github/workflows/deploy-worker.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-worker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers/shv-api

    steps:
      - uses: actions/checkout@v4

      # Kiểm tra code có patch ward + weight
      - name: Verify source markers
        run: |
          grep -n "/shipping/areas/ward" src/index.js || true
          grep -n "payload.weight = Number(body.weight_gram" src/index.js || true

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}   # Tạo secret tên **CF_ACCOUNT_ID**
          workingDirectory: workers/shv-api
          command: publish
