name: Deploy Worker

on:
  push:
    paths:
      - "workers/shv-api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Bật debug log cho Actions (để xem chi tiết nếu còn lỗi)
      ACTIONS_STEP_DEBUG: "true"
      ACTIONS_RUNNER_DEBUG: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree + wrangler.toml
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "---- workers/shv-api ----"
          ls -la workers/shv-api || true
          echo "---- wrangler.toml ----"
          cat workers/shv-api/wrangler.toml || true

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Wrangler version
        working-directory: workers/shv-api
        run: npx --yes wrangler@3 --version

      - name: Whoami
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 whoami --verbose

      - name: Deploy (direct)
        working-directory: workers/shv-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: npx --yes wrangler@3 deploy --verbose
