name: Deploy Worker
on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - ".github/workflows/deploy-worker.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: api/pnpm-lock.yaml

      - name: Install deps
        working-directory: api
        run: |
          pnpm i --frozen-lockfile || pnpm i

      - name: Build
        working-directory: api
        run: pnpm run -C . build || echo "skip build"

      - name: Check secrets presence
        run: |
          test -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" || (echo "❌ Missing CLOUDFLARE_API_TOKEN" && exit 1)
          test -n "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" || (echo "❌ Missing CLOUDFLARE_ACCOUNT_ID" && exit 1)

      - name: Publish Worker
        uses: cloudflare/wrangler-action@v3
# hoặc pin: cloudflare/wrangler-action@v3.7.0

        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: api
          command: deploy --config wrangler.toml
